package com.springboot.api.enums;

/**
 * TypeModule
 */
public enum TypeModule {
    MODULE_MANAGEMENT_USER,
    MODULE_HUMAN_RESOURCE,
    MODULE_INVENTORY,
    MODULE_SALES_AND_MARKETING,
    MODULE_PURCHASE,
    MODULE_FINANCE_AND_ACCOUNTING,
    MODULE_CUSTOMES_RELATIONSHIP_MANAGEMENT,
    MODULE_SUPPLY_CHAIN_MANAGEMENT;
}
